### ISSUE TITLE
Library broken on NPM

### ISSUE THREAD

**Issue by nicola** [linkeddata/rdflib.js#64] opened 2015-06-29 17:22 UTC
This is the second broken build on NPM, this is a clear call to have tests & travis soon!

```
/Users/mozilla/Proj/gits/node-webid/node_modules/rdflib/dist/rdflib.js:21085
module.exports = jsonldjs;
                 ^
ReferenceError: jsonldjs is not defined
    at Object.<anonymous> (/Users/mozilla/Proj/gits/node-webid/node_modules/rdflib/dist/rdflib.js:21085:18)
    at Object../request (/Users/mozilla/Proj/gits/node-webid/node_modules/rdflib/dist/rdflib.js:21086:4)
    at s (/Users/mozilla/Proj/gits/node-webid/node_modules/rdflib/dist/rdflib.js:7488:254)
    at /Users/mozilla/Proj/gits/node-webid/node_modules/rdflib/dist/rdflib.js:7488:305
    at Object.async (/Users/mozilla/Proj/gits/node-webid/node_modules/rdflib/dist/rdflib.js:24032:14)
    at s (/Users/mozilla/Proj/gits/node-webid/node_modules/rdflib/dist/rdflib.js:7488:254)
    at e (/Users/mozilla/Proj/gits/node-webid/node_modules/rdflib/dist/rdflib.js:7488:425)
    at /Users/mozilla/Proj/gits/node-webid/node_modules/rdflib/dist/rdflib.js:7488:443
    at Object.<anonymous> (/Users/mozilla/Proj/gits/node-webid/node_modules/rdflib/dist/rdflib.js:25646:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mozilla/Proj/gits/node-webid/test/webid.js:1:76)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/mozilla/Proj/gits/node-webid/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/mozilla/Proj/gits/node-webid/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/Users/mozilla/Proj/gits/node-webid/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/Users/mozilla/Proj/gits/node-webid/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by martinmr** [comment] 2015-06-29 17:38
How did you trigger the error? It seems to be an error in jsonld.js, not in our own code. I could try changing the version of jsonld.js to an earlier one and see if that fixes the bug.

**Comment by martinmr** [comment] 2015-06-29 17:40
Confirmed: It's an issue with jsonld.js support for browserify. Check this issue: https://github.com/digitalbazaar/jsonld.js/issues/92

**Comment by martinmr** [comment] 2015-06-29 17:52
I belive the issue it's fixed by upgrading to a new version. The line is no longer there in the rdflib.js file.     I am going to wait before upgrading to a new version on npm to make sure the issue is gone.

**Comment by nicola** [comment] 2015-07-12 23:33
has this been fixed?

**Comment by martinmr** [comment] 2015-07-13 02:04
Yes.

On Sun, Jul 12, 2015 at 7:33 PM, Nicola Greco <notifications@github.com>
wrote:

> has this been fixed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linkeddata/rdflib.js/issues/64#issuecomment-120773235>
> .
>



-- 
Martin Martinez Rivera
Massachusetts Institute of Technology
Courses 6-3
Class of 2014

**Closed** 2015-07-13 03:09 UTC
Labels: bug
