### ISSUE TITLE
When retying without credentials, promise seems to be lost

### ISSUE THREAD

**Issue by timbl** [linkeddata/rdflib.js#326] opened 2019-07-16 16:03 UTC
The system retries and succeeds but the original code does not seem to run as a result. 
This is code on the add-id-fix-getHeader branch
```
Dropped on thing <https://campuse.ro/signup/>
fetcher.js:2086  setCredentials: https://campuse.ro/signup/ starts as: undefined
fetcher.js:2098    setCredentials: https://campuse.ro/signup/ ends as: include
tabbed.ttl#this:1 Access to fetch at 'https://campuse.ro/signup/' from origin 'https://timbl.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
fetcher.js:851 Fetcher: <https://campuse.ro/signup/> Non-HTTP fetch exception: TypeError: Failed to fetch
fetcher.js:1593 Fetcher: CORS: RETRYING with NO CREDENTIALS for <https://campuse.ro/signup/>
fetcher.js:2086  setCredentials: https://campuse.ro/signup/ starts as: false
fetcher.js:2098    setCredentials: https://campuse.ro/signup/ ends as: false
```

**Comment by RubenVerborgh** [comment] 2019-08-15 12:23
`add-id-fix-getHeader` got merged to `master`, so following up there

**Comment by RubenVerborgh** [comment] 2019-08-15 12:31
Ran in to https://github.com/linkeddata/rdflib.js/issues/334, fixing that first.

**Comment by RubenVerborgh** [comment] 2019-08-17 15:45
Was able to reproduce the above with:

```javascript
  (async () => {
    const store = $rdf.graph();
    const fetcher = new $rdf.Fetcher(store);
    const result = await fetcher.load('https://campuse.ro/signup/');
    console.log('result', result);
  })();
```

However, some context is missing, namely:

```
 setCredentials: https://campuse.ro/signup/ starts as: undefined fetcher.js:583:12
   setCredentials: https://campuse.ro/signup/ ends as: include fetcher.js:591:12
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://campuse.ro/signup/’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).
Fetcher: <https://campuse.ro/signup/> Non-HTTP fetch exception: TypeError: NetworkError when attempting to fetch resource. fetcher.js:814:22
Fetcher: CORS: RETRYING with NO CREDENTIALS for <https://campuse.ro/signup/> fetcher.js:1431:12
 setCredentials: https://campuse.ro/signup/ starts as: false fetcher.js:583:12
   setCredentials: https://campuse.ro/signup/ ends as: false fetcher.js:591:12
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://campuse.ro/signup/. (Reason: CORS request did not succeed).
```

So after the first request hits a CORS block, it is being retried, but hits a second CORS block:
1. Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’
2. The Same Origin Policy disallows reading the remote resource at https://campuse.ro/signup/

And that second request is not even being sent to the server, so something in the first CORS preflight already blocks it.

**Comment by RubenVerborgh** [comment] 2019-08-17 17:59
Found the problem and created a fix in https://github.com/linkeddata/rdflib.js/pull/338.

The root cause of the problem is, in my opinion, the complexity of the fetcher code. Several of its concerns are spread out across multiple places. In this case, the error handling code was interfering with the retried request.

The concrete problem here was the following:
1. `cleanupFetchRequest` was not being fired, because no timeout occurred
2. this resulted in the failed response remaining in `fetchQueue`
3. this resulted in `pendingFetchPromise` reusing the existing (already failed) promise
4. but that promise never resolved, because it was (indirectly) being resolved to itself
5. therefore, it remained in an eternal pending state

The deeper fix is to untangle the fetch/error/retry logic. I have looked into fixing 1 ensuring that `cleanupFetchRequest` is also called in case of errors. However, the error is caught before `pendingFetchPromise` can deal with it, and it is caught by spinning up the next request. Refactoring this would likely break other code that is being depended on.

So I settled for manually removing it from the `fetchQueue`: https://github.com/linkeddata/rdflib.js/pull/338/commits/daad18fef5293067b65fd6e387e1dad00a3ef6bd. However, in the longer term, we probably want to ensure that the deletion from `fetchQueue` only happens in one place (it currently happens in multiple).

An additional problem was that `credentials` was set to `false` instead of `'omit'`, which I fixed in https://github.com/linkeddata/rdflib.js/pull/338/commits/7b5c9f66a9c81a0be5eb46177f535ca72416bbcd.

**Closed** 2019-08-19 11:56 UTC
Labels: bug
